name: NASA Full-stack CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 16 to install server & client modules!
        uses: actions/setup-node@v3
        with:
          node-version: 18
        run: npm run install-server
        run: npm run install-client
      - name: Use Node.js version 18 to build client
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: npm run build --prefix client