name: NASA Full-stack CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing Modules and building with NPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run install-server
      - run: npm run install-client
      - run: npm run build --prefix client