name: NASA Fullstack CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build: 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 16
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run install-server